"""change_ids_to_uuid

Revision ID: 002
Revises: 001
Create Date: 2024-01-31 00:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop existing indexes
    op.drop_index('ix_enrollments_id', table_name='enrollments')
    op.drop_index('ix_courses_id', table_name='courses')
    op.drop_index('ix_users_id', table_name='users')
    
    # Change enrollments table first (since it has foreign keys)
    op.alter_column('enrollments', 'id', type_=postgresql.UUID(as_uuid=True), postgresql_using='uuid_generate_v4()')
    op.alter_column('enrollments', 'user_id', type_=postgresql.UUID(as_uuid=True))
    op.alter_column('enrollments', 'course_id', type_=postgresql.UUID(as_uuid=True))
    
    # Change courses table
    op.alter_column('courses', 'id', type_=postgresql.UUID(as_uuid=True), postgresql_using='uuid_generate_v4()')
    
    # Change users table
    op.alter_column('users', 'id', type_=postgresql.UUID(as_uuid=True), postgresql_using='uuid_generate_v4()')
    
    # Recreate indexes
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('ix_enrollments_id', table_name='enrollments')
    op.drop_index('ix_courses_id', table_name='courses')
    op.drop_index('ix_users_id', table_name='users')
    
    # Change back to Integer
    op.alter_column('enrollments', 'id', type_=sa.Integer())
    op.alter_column('enrollments', 'user_id', type_=sa.Integer())
    op.alter_column('enrollments', 'course_id', type_=sa.Integer())
    
    op.alter_column('courses', 'id', type_=sa.Integer())
    op.alter_column('users', 'id', type_=sa.Integer())
    
    # Recreate indexes
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    
    # ### end Alembic commands ###